### ISSUE TITLE
所以引导在哪？

### ISSUE THREAD

**Issue by aboutabout** [CoolestEnoch/Dell-G5-5500-opencore#1]
1

**Comment by CoolestEnoch** [comment]
如果release都懒得翻，那我也没必要给你提供更多信息了。

**Comment by CoolestEnoch** [comment]
草，我的锅，忘记上传了，一会儿马上补到release 里

**Comment by aboutabout** [comment]
我中午确实是没看到有，只有自述文件，现在有了🤗

**Comment by CoolestEnoch** [comment]
草，原来是上次上传卡着了
![屏幕截图 2023-05-31 172134](https://github.com/CoolestEnoch/Dell-G5-5500-opencore/assets/77060301/7a31a07b-3a91-43e3-a477-454e135f6d07)
<br/>
已上传，可去release里下载
