### ISSUE TITLE
macOS Sonoma 14.0支持吗？

### ISSUE THREAD

**Issue by iamleehom** [CoolestEnoch/Dell-G5-5500-opencore#2]
请问macOS Sonoma 14.0支持吗？

**Comment by CoolestEnoch** [comment]
在线蹲一个正式版的镜像，魏叔那个要付费
白嫖怪.jpg（逃
![Uploading Screenshot_2023-10-07-18-31-45-495_tv.danmaku.bili.jpg…]()

**Comment by iamleehom** [comment]
链接: https://pan.baidu.com/s/1dKFzJaNOR0w6ZsDF3S9IAg 
提取码: 2ij5

你看这行吗？

**Comment by CoolestEnoch** [comment]
这个文件我看了一下，不行XD
这个iso里不带efi分区，我甚至连安装盘都无法烧录（

**Comment by CoolestEnoch** [comment]
在做了，嫑急

**Comment by CoolestEnoch** [comment]
现已支持Mac OS 14 Sonoma
https://github.com/CoolestEnoch/Dell-G5-5500-opencore/releases/tag/0.9.5

**Comment by CoolestEnoch** [comment]
现已支持Mac OS 14 Sonoma
https://github.com/CoolestEnoch/Dell-G5-5500-opencore/releases/tag/0.9.5
