### ISSUE TITLE
cpu发热

### ISSUE THREAD

**Issue by mucute** [CoolestEnoch/Dell-G5-5500-opencore#3]
cpu开机温度一直保持在80度
windows开机差不多保持在50度
您有解决办法么，请给我您的联系方式，谢谢

**Comment by CoolestEnoch** [comment]
关闭处理器睿频，处理器温度不会超过60摄氏度。可以去bios里关(这样会影响本机上所有的系统)，也可以在需要关闭的系统里关(这样不影响别的系统)。
我是在MacOS里下了个Turbo Boost Switcher关闭处理器睿频的，相关文章可参考[这里](https://sspai.com/post/35224)。

我也觉得奇怪啊，这电脑MacOS能跑这么高温度？我经常Windows下100度，但是Linux下跑AOSP编译温度撑死75度，，，

**Comment by mucute** [comment]
我试了CpuFriend.kext也不起作用

**Comment by CoolestEnoch** [comment]
> 我试了CpuFriend.kext也不起作用

这电脑目前我没成功在上面让处理器正常变频，所以我的建议还是关闭处理器睿频。

**Comment by mucute** [comment]
好的谢谢

**Comment by mucute** [comment]
我试了那个应用，开启之后cpu温度还是高

**Comment by CoolestEnoch** [comment]
清下灰呢？我电脑现在不管怎么折腾温度一直低于80度，，，

还有，你确定是i5版的G5 5500？

**Comment by mucute** [comment]
我是i7

**Comment by CoolestEnoch** [comment]
[Read this before open an issue.](https://github.com/CoolestEnoch/Dell-G5-5500-opencore/blob/main/README.md)



[Dell官方手册](https://www.dell.com/support/manuals/zh-cn/g-series-15-5500-laptop/dell-g5-15-5500-setup-and-specifications/%E6%88%B4%E5%B0%94-g5-15-5500%E7%9A%84%E8%A7%84%E6%A0%BC?guid=guid-7c9f07ce-626e-44ca-be3a-a1fb036413f9&lang=zh-cn)显示i5和i7两个型号配置差异还是很大的，不建议把该仓库opencore这些有针对适配的东西进行混用。


附图：i7和i5在肉眼可见不明显的差异**之一**（后面的是i5前面的是i7，i7机器不是我的是我借来的）
![IMG_20220425_225923](https://github.com/CoolestEnoch/Dell-G5-5500-opencore/assets/77060301/0f8b9932-9273-4248-8426-3d5473273d9e)
