### ISSUE TITLE
关机不断电

### ISSUE THREAD

**Issue by mucute** [CoolestEnoch/Dell-G5-5500-opencore#4]
你存在这个问题么

**Comment by CoolestEnoch** [comment]
我电脑没这个问题，反而我另一台电脑在Linux下存在偶现的[关机耗电问题](https://github.com/linux-surface/linux-surface/issues/1227)。

参考我Linux系统下的做法？
电脑使用[rEFInd](https://www.rodsbooks.com/refind/)作为多系统引导器(装了四个系统，用这玩意切换起来方便)，当存在疑似关机不彻底问题的时候选择重启而非关机，重启进入rEFInd后在rEFInd里选择关机，这里能把电脑彻底关掉。

**Comment by mucute** [comment]
我再oc0.8.8打了断电补丁之后可以正常关机，但是在你提供的efi中失效了，不知道是什么原因:)

**Comment by CoolestEnoch** [comment]
https://github.com/CoolestEnoch/Dell-G5-5500-opencore/issues/3#issuecomment-1926243354
